### PR TITLE
financroo ui feature flag handling in server

### PR DESCRIPTION
**Pull request by ksroda-ce**
This PR introduces feature flags server handling for UI features in Financroo. It will be used during the work on the Investments view.

### CODE REVIEW

**Comment by holowinski** [comment]
I think this should be handled differently.

We should have a flag in financroo app configuration, disabled by default.
We don't need to expose this via API.

We should return feature configuration object to the frontend and disable stuff based on that.

Additionally, APIs responsible for handling payments should be disabled later on.

**Comment by ksroda-ce** [comment]
> I think this should be handled differently.
> 
> We should have a flag in financroo app configuration, disabled by default.
> We don't need to expose this via API.
> 
> We should return feature configuration object to the frontend and disable stuff based on that.
> 
> Additionally, APIs responsible for handling payments should be disabled later on.


@holowinski So we will need to add the logic to the frontend side that fetches configuration, stores globally the config and dynamically shows/hides views after initial render. I thought my approach was much simpler, it just requires in ui a simple check on the document.cookie in render. What do you think?

**Comment by ikawalec** [comment]
> > I think this should be handled differently.
> > We should have a flag in financroo app configuration, disabled by default.
> > We don't need to expose this via API.
> > We should return feature configuration object to the frontend and disable stuff based on that.
> > Additionally, APIs responsible for handling payments should be disabled later on.
> 
> @holowinski So we will need to add the logic to the frontend side that fetches configuration, stores globally the config and dynamically shows/hides views after initial render. I thought my approach was much simpler, it just requires in ui a simple check on the document.cookie in render. What do you think?

@ksroda-ce You could reuse this config: https://github.com/cloudentity/openbanking-sandbox/blob/4e93c66d31b7b43ce830cd298907b2614b317522/financroo/server.go#L100

**Comment by ksroda-ce** [comment]
> > > I think this should be handled differently.
> > > We should have a flag in financroo app configuration, disabled by default.
> > > We don't need to expose this via API.
> > > We should return feature configuration object to the frontend and disable stuff based on that.
> > > Additionally, APIs responsible for handling payments should be disabled later on.
> > 
> > 
> > @holowinski So we will need to add the logic to the frontend side that fetches configuration, stores globally the config and dynamically shows/hides views after initial render. I thought my approach was much simpler, it just requires in ui a simple check on the document.cookie in render. What do you think?
> 
> @ksroda-ce You could reuse this config:
> 
> https://github.com/cloudentity/openbanking-sandbox/blob/4e93c66d31b7b43ce830cd298907b2614b317522/financroo/server.go#L100

So I just thought that I can place in this config feature flag keys and make this enable/disable endpoints more generic - so they will read from this config what specific features can be turned on/of?

**Comment by holowinski** [comment]
We don't really want to enable those feature flags dynamically, either the application starts with a feature or it doesn't.
Similar to other applications, we don't want people to actually change what the application does by just calling an API.

I was suggesting something similar to what @ikawalec proposed.
Looking at the WebConfig implementation, it looks like the place to put FFs in.

I would create a 

`type FeatureFlags struct {
  Investments string
}`

in `financroo/config.go` and expose the whole thing in 

`func (s *Server) WebConfig()`

 via something like 

```
	return func(c *gin.Context) {
		c.JSON(200, gin.H{
            ...
			"featureFlags:            s.Config.FeatureFlags,
		})
	}
```

**Comment by ksroda-ce** [comment]
@holowinski @ikawalec  I've made changes to not use this endpoint approach, instead I'm using config and passing its feature flags to the HTML, so no extra API calls will be needed:
`		c.HTML(http.StatusOK, "index.html", gin.H{ "featureFlags": s.Config.FeatureFlags })`

**Review by mbilski — APPROVED** [review]

**Review by ikawalec — APPROVED** [review]

**Pull request merged**
